# -*- coding: utf-8 -*-
"""Amazon Reviews - Final Assignement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_aRFEO1cPqBZ0PPN0tDzhB3WqftCDV7

# ***Amazon Reviews***

**Project Overview**

This project addresses the task of sentiment analysis on Amazon product reviews, aiming to classify each review as positive or negative. The analysis compares classical natural language processing techniques with modern transformer-based models, using the same dataset and evaluation protocol to ensure a fair comparison.

# Imports
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import os, re, random, math
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split

!pip install gensim
from gensim.models import Word2Vec

!pip -q install -U pandas numpy scikit-learn gensim nltk tqdm matplotlib \
     "transformers>=4.40,<5" datasets tensorflow

os.environ["TF_USE_LEGACY_KERAS"] = "1"

from transformers import AutoTokenizer, TFDistilBertModel
import tensorflow as tf

import gensim.downloader as api

# Uninstall potentially conflicting versions first
!pip uninstall -y numpy pyarrow datasets transformers

# Install a compatible numpy version that is known to work and has wheels for Py3.12
# numpy==1.26.4 is a good candidate, as numpy 2.x caused issues for pyarrow previously.
!pip install numpy==1.26.4

# Reinstall datasets, pyarrow, and transformers, letting pip resolve compatible versions
# pyarrow should be compatible with numpy 1.26.4
!pip install datasets pyarrow transformers

from datasets import Dataset
from transformers import TFDistilBertForSequenceClassification, DataCollatorWithPadding

!pip install wordcloud

from google.colab import drive
drive.mount('/content/drive')

"""# Load Data and Preprocessing"""

path = '/content/drive/MyDrive/Amazon_Unlocked_Mobile.csv'
df = pd.read_csv(path)

"""The dataset consists of Amazon Unlocked Mobile reviews. Reviews with a rating equal to 3 are removed, as they represent neutral sentiment. The remaining reviews are mapped to a binary label:


*   Ratings greater than 3 are labeled as positive
*   Ratings lower than 3 are labeled as negative

To improve computational efficiency while preserving class balance, a stratified 30% subset of the dataset is used. Missing values in the review text and ratings are removed.
"""

df = df[df["Rating"] != 3].copy()
df = df.dropna(subset=["Reviews", "Rating"]).copy()
df["Positively Rated"] = np.where(df["Rating"] > 3, 1, 0)
df["label"] = (df["Rating"] > 3).astype(int)

df.info()

df.info()

"""Using a smaller number of entries for faster computation while maintaining positive/negative ratio."""

PERCENT = 0.3

df_small, _ = train_test_split(
    df,
    train_size=PERCENT,
    stratify=df["label"]
)

df = df_small

df.head(10)

"""Metrics"""

def show_results(name, y_true, y_pred):
    print(f"\n=== {name} ===")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("F1:", f1_score(y_true, y_pred))
    print(classification_report(y_true, y_pred, digits=4))

results = []

def store_result(name, y_true, y_pred):
    results.append({
        "model": name,
        "accuracy": accuracy_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred)
    })

"""Cleaning Functions

Two separate preprocessing pipelines are applied, depending on the model family:

Classical Models (Word2Vec, GloVe)

*   Lowercasing
*   Removal of URLs and special characters
*  Tokenization
*   Stopword removal
*   Stemming


This preprocessing reduces noise and improves the quality of averaged word embeddings.

Transformer-Based Models (BERT)

*   Minimal preprocessing
*   Lowercasing and removal of URLs only


Stopwords and word structure are preserved, as BERT relies on contextual and syntactic information.
"""

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

def clean_text(s):
    s = str(s).lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)
    s = re.sub(r"[^a-z0-9\s']", " ", s)
    s = re.sub(r"\s+", " ",s).strip()
    s = re.sub(r'#', '', s)
    words = s.split()
    processed_words = [stemmer.stem(word) for word in words if word not in stop_words]

    return processed_words

def clean_text_bert(s):
    s = str(s).lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    s = re.sub(r'#', '', s)
    return s

processed_reviews = df["Reviews"].apply(clean_text)

processed_reviews

df["tokens"] = processed_reviews   # W2V/GloVe
df["bert_text"] = df["Reviews"].apply(clean_text_bert)  # BERT

"""Train / Validation / Test Split


The dataset is split into training, validation, and test sets using stratified sampling to maintain the class distribution across all splits.
The same split is used for all models.

For Word2Vec and GloVe, empty reviews produced after preprocessing are removed from all splits to avoid invalid input. Separate label arrays are maintained to prevent misalignment between token-based and BERT-based models.
"""

#Train+Val / Test
trainval_df, test_df = train_test_split(
    df,
    test_size=0.25,
    stratify=df["label"])

#Train / Validation
train_df, val_df = train_test_split(
    trainval_df,
    test_size=0.2,          # 20% του trainval
    stratify=trainval_df["label"])

# Tokens (Word2Vec / GloVe)
Xtok_train = train_df["tokens"].tolist()
Xtok_val   = val_df["tokens"].tolist()
Xtok_test  = test_df["tokens"].tolist()

# Text (BERT)
Xbert_train = train_df["bert_text"].tolist()
Xbert_val   = val_df["bert_text"].tolist()
Xbert_test  = test_df["bert_text"].tolist()

# Labels
y_train = train_df["label"].values
y_val   = val_df["label"].values
y_test  = test_df["label"].values

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

# --- Keep separate labels for token models vs BERT models ---
y_tok_train = y_train.copy()
y_tok_val   = y_val.copy()
y_tok_test  = y_test.copy()

y_bert_train = y_train.copy()
y_bert_val   = y_val.copy()
y_bert_test  = y_test.copy()

len(Xtok_train)

"""Filter out empty reviews (after preprocessing)

"""

def filter_empty_token_reviews(Xtok, y):
    mask = np.array([len(t) > 0 for t in Xtok])
    Xtok_f = [t for t, m in zip(Xtok, mask) if m]
    y_f = y[mask]
    return Xtok_f, y_f

# Filter TRAIN/VAL/TEST for W2V/GloVe (only tokens + labels)
Xtok_train, y_tok_train = filter_empty_token_reviews(Xtok_train, y_tok_train)
Xtok_val,   y_tok_val   = filter_empty_token_reviews(Xtok_val,   y_tok_val)
Xtok_test,  y_tok_test  = filter_empty_token_reviews(Xtok_test,  y_tok_test)

print("After filtering:")
print("Train:", len(Xtok_train), len(y_tok_train))
print("Val:",   len(Xtok_val),   len(y_tok_val))
print("Test:",  len(Xtok_test),  len(y_tok_test))

"""# Logistic Regression

## Word2Vec

Word2Vec embeddings are trained on the tokenized training reviews. Each review is converted into a single fixed-length vector by averaging the Word2Vec embeddings of all its words and these vectors are stacked to form the input matrix for the classifier, producing a fixed-length numerical representation. A Logistic Regression classifier is then trained on these vectors.
"""

EMBED_DIM = 100

w2v = Word2Vec(
    sentences=Xtok_train,
    vector_size=EMBED_DIM,
    window=5,
    min_count=2,
    workers=os.cpu_count() or 2
)

def review_to_vector(word_list, word2vec_model, embedding_dim):
    word_vectors = [
        word2vec_model.wv[word]
        for word in word_list
        if word in word2vec_model.wv
    ]

    if len(word_vectors) == 0:
        return np.zeros(embedding_dim)

    return np.mean(word_vectors, axis=0)

train_vectors = np.vstack([review_to_vector(r, w2v, 100) for r in Xtok_train])
test_vectors  = np.vstack([review_to_vector(r, w2v, 100) for r in Xtok_test])

print("train_vectors:", train_vectors.shape)
print("test_vectors:", test_vectors.shape)
print("y_train:", len(y_tok_train))
print("y_test:", len(y_tok_test))

# Train classifier
model = LogisticRegression(max_iter=2000)
model.fit(train_vectors, y_tok_train)

# Predict
test_predictions = model.predict(test_vectors)

show_results("(a) Word2Vec + Logistic Regression (TEST)", y_tok_test, test_predictions)

store_result("Word2Vec + LR", y_tok_test, test_predictions)

"""## Glove + Logistic Regression"""

glove = api.load("glove-wiki-gigaword-100")
glove2 = api.load("glove-wiki-gigaword-200")
glove3 = api.load("glove-wiki-gigaword-300")

def glove_review_to_vector(word_list, model, embedding_dim):
    word_vectors = [
        model[word]
        for word in word_list
        if word in model
    ]

    if len(word_vectors) == 0:
        return np.zeros(embedding_dim)

    return np.mean(word_vectors, axis=0)

GLOVE_DIM = glove2.vector_size

Xtr_glove = np.vstack([glove_review_to_vector(r, glove2, GLOVE_DIM) for r in Xtok_train])
Xte_glove = np.vstack([glove_review_to_vector(r, glove2, GLOVE_DIM) for r in Xtok_test])

glove_lr = LogisticRegression(max_iter=2000)
glove_lr.fit(Xtr_glove, y_tok_train)
pred_glove = glove_lr.predict(Xte_glove)

show_results("(b) GloVe + Logistic Regression (TEST)", y_tok_test, pred_glove)

store_result("GloVe + LR", y_tok_test, pred_glove)

"""## BERT embeddings + Logistic Regression (TensorFlow)

In this approach, DistilBERT is used as a frozen feature extractor. Each review is passed through the BERT encoder, and the representation of the first token is used as a sentence-level embedding. These embeddings are then classified using Logistic Regression.
"""

MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

bert_encoder = TFDistilBertModel.from_pretrained(
    MODEL_NAME,
    from_pt=True,
    use_safetensors=False
)
bert_encoder.trainable = False

from tqdm.notebook import tqdm

def cls_embeddings_tf_batched(texts, tokenizer, model, batch_size=32, max_length=128):
    embeddings = []
    # Processing per batches for speed
    for i in tqdm(range(0, len(texts), batch_size), desc="Processing batches"):
        batch_texts = texts[i : i + batch_size]

        # Tokenization
        tokens = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            return_tensors="tf",
            max_length=max_length
        )

        # Inference
        outputs = model(**tokens, training=False)
        cls_vectors = outputs.last_hidden_state[:, 0, :]
        embeddings.append(cls_vectors.numpy())

    if embeddings:
        return np.vstack(embeddings)
    else:
        return np.array([])

"""Checking length of X_train to avoid errors"""

print(len(Xbert_train), len(y_bert_train))

# Export embeddings
Xtr_bert = cls_embeddings_tf_batched(Xbert_train, tokenizer, bert_encoder, batch_size=32)
Xte_bert = cls_embeddings_tf_batched(texts=Xbert_test, tokenizer=tokenizer, model=bert_encoder, batch_size=32)
print(Xtr_bert.shape[0], len(y_bert_train))
#  Logistic Regression
bert_lr = LogisticRegression(max_iter=3000, C=0.5)
bert_lr.fit(Xtr_bert, y_bert_train)
pred_bert = bert_lr.predict(Xte_bert)

"""The results confirm that transformer-based models outperform classical NLP approaches, with fine-tuned BERT providing the best trade-off between precision and recall on this dataset, even when trained on a reduced subset of the data."""

show_results("(c) BERT embeddings + Logistic Regression (TEST)", y_bert_test, pred_bert)

store_result("BERT emb + LR", y_bert_test, pred_bert)

"""# Summary LR

Models are evaluated using Accuracy and F1-score.
"""

summary_lr = pd.DataFrame(results).sort_values("f1", ascending=False)
print("\n=== SUMMARY (sorted by F1) ===")
print(summary_lr)

"""for 30% of the data

# Pooling vs CLS
"""

def get_mean_bert_embeddings_batched(texts, tokenizer, model, batch_size=32, max_length=128):
    embeddings = []
    for i in tqdm(range(0, len(texts), batch_size), desc="Processing batches for mean pooling"):
        batch_texts = texts[i : i + batch_size]

        # Tokenization
        tokens = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            return_tensors="tf",
            max_length=max_length
        )

        # Inference to get hidden states
        outputs = model(**tokens, training=False)
        last_hidden_state = outputs.last_hidden_state

        # Create attention mask to identify non-padding tokens
        attention_mask = tf.cast(tokens["attention_mask"], tf.float32)
        attention_mask = tf.expand_dims(attention_mask, axis=-1) # Expand mask to match hidden state dimensions

        # Multiply hidden states by the attention mask to zero out padding token embeddings
        masked_embeddings = last_hidden_state * attention_mask

        # Calculate sum of masked embeddings along the token dimension (axis=1)
        sum_masked_embeddings = tf.reduce_sum(masked_embeddings, axis=1)

        # Calculate sum of attention mask along the token dimension (axis=1)
        # Ensure minimum value of 1 to avoid division by zero
        sum_attention_mask = tf.maximum(tf.reduce_sum(attention_mask, axis=1), 1e-9)

        # Divide summed embeddings by summed mask to get mean-pooled embeddings
        mean_pooled_embeddings = sum_masked_embeddings / sum_attention_mask

        embeddings.append(mean_pooled_embeddings.numpy())

    if embeddings:
        return np.vstack(embeddings)
    else:
        return np.array([])

print("Defined get_mean_bert_embeddings_batched function.")

Xtr_bert_mean = get_mean_bert_embeddings_batched(Xbert_train, tokenizer, bert_encoder, batch_size=32)
Xte_bert_mean = get_mean_bert_embeddings_batched(Xbert_test, tokenizer, bert_encoder, batch_size=32)

print(f"Shape of Xtr_bert_mean: {Xtr_bert_mean.shape}")
print(f"Shape of Xte_bert_mean: {Xte_bert_mean.shape}")

bert_lr_mean = LogisticRegression(max_iter=3000, C=0.5)
bert_lr_mean.fit(Xtr_bert_mean, y_bert_train)

print("Logistic Regression model (bert_lr_mean) trained successfully with mean-pooled BERT embeddings.")

pred_bert_mean = bert_lr_mean.predict(Xte_bert_mean)
show_results("(e) BERT mean-pooled embeddings + Logistic Regression (TEST)", y_bert_test, pred_bert_mean)
store_result("BERT mean-pooled + LR", y_bert_test, pred_bert_mean)

summary = pd.DataFrame(results).sort_values("f1", ascending=False)
print("\n=== UPDATED SUMMARY (sorted by F1) ===")
print(summary)

"""# Bert fine-tuning

Finally, DistilBERT is fine-tuned end-to-end for sentiment classification by adding a classification head on top of the encoder. The model is trained for three epochs, with early stopping based on validation loss to reduce overfitting.

This approach represents the most expressive and computationally intensive model in the study.
"""

train_ds = Dataset.from_dict({"text": Xbert_train, "label": y_bert_train.tolist()})
val_ds   = Dataset.from_dict({"text": Xbert_val,   "label": y_bert_val.tolist()})
test_ds  = Dataset.from_dict({"text": Xbert_test,  "label": y_bert_test.tolist()})

def tokenize_batch(batch):
    return tokenizer(batch["text"], truncation=True)

train_tok = train_ds.map(tokenize_batch, batched=True, remove_columns=["text"])
val_tok   = val_ds.map(tokenize_batch,   batched=True, remove_columns=["text"])
test_tok  = test_ds.map(tokenize_batch,  batched=True, remove_columns=["text"])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

tf_train = train_tok.to_tf_dataset(
    columns=["input_ids", "attention_mask"],
    label_cols=["label"],
    shuffle=True,
    batch_size=16,
    collate_fn=data_collator,
)

tf_val = val_tok.to_tf_dataset(
    columns=["input_ids", "attention_mask"],
    label_cols=["label"],
    shuffle=False,
    batch_size=32,
    collate_fn=data_collator,)

tf_test = test_tok.to_tf_dataset(
    columns=["input_ids", "attention_mask"],
    label_cols=["label"],
    shuffle=False,
    batch_size=32,
    collate_fn=data_collator,)

ft_model = TFDistilBertForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
    from_pt=True,
    use_safetensors=False
)

"""The model was fine-tuned for three epochs, with validation monitoring to limit overfitting."""

ft_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy("accuracy")])

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=1,
    restore_best_weights=True)

ft_model.fit(tf_train, validation_data=tf_val, epochs=3, callbacks=[early_stop])

pred = ft_model.predict(tf_test)
pred_bert_ft = np.argmax(pred.logits, axis=1)

show_results("(d) BERT fine-tuning (TEST)", y_bert_test, pred_bert_ft)
store_result("BERT fine-tune", y_bert_test, pred_bert_ft)

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_bert_test,
    pred_bert_ft,
    display_labels=["Negative", "Positive"],
    cmap="Blues"
)

plt.title("Confusion Matrix – BERT fine-tuning")
plt.show()

"""# Summary"""

summary = pd.DataFrame(results).sort_values("f1", ascending=False)
print("\n=== Final SUMMARY (sorted by F1) ===")
print(summary)

"""# Example Reviews"""

example_reviews = [
    "Amazing phone, great battery life and fast delivery!",
    "Terrible quality, the screen broke in two days.",
    "Good value for money, works well and looks nice.",
    "I wanted to love it, but the screen flickers sometimes and it's annoying.",
    "It’s okay for the price, but I wouldn’t recommend it to anyone.",
    "Sound is loud, yet the microphone is so bad people can’t hear me.",
    "After the update it became slower, but at least it looks nice.",
    "I’m not saying it’s terrible… I’m just saying I returned it the next day.",
    "This is the best phone I've ever bought (until it stopped turning on).",
    "Worst purchase ever, not working and customer support is bad.",
]

def to_sentiment(pred):
    return "POSITIVE" if int(pred) == 1 else "NEGATIVE"

# ============================================================
# (a) Word2Vec + Logistic Regression
# ============================================================
print("\n================ (a) Word2Vec + LR ================")
for text in example_reviews:
    tokens = clean_text(text)  # returns list of tokens
    x = review_to_vector(tokens, w2v, 100).reshape(1, -1)
    pred = model.predict(x)[0]
    print(f"\nText: {text}\nPrediction: {to_sentiment(pred)}")

# ============================================================
# (b) GloVe + Logistic Regression
# ============================================================
print("\n================ (b) GloVe + LR ================")
for text in example_reviews:
    tokens = clean_text(text)
    x = glove_review_to_vector(tokens, glove, glove.vector_size).reshape(1, -1)
    pred = glove_lr.predict(x)[0]
    print(f"\nText: {text}\nPrediction: {to_sentiment(pred)}")

# ============================================================
# (c) BERT embeddings + Logistic Regression
# ============================================================
print("\n================ (c) BERT embeddings + LR ================")

def single_bert_embedding(text, max_length=128):
    # minimal cleaning for BERT
    text = clean_text_bert(text)
    tokens = tokenizer(text, truncation=True, padding=True, max_length=max_length, return_tensors="tf")
    outputs = bert_encoder(**tokens, training=False)
    cls_vec = outputs.last_hidden_state[:, 0, :].numpy()  # shape (1, hidden)
    return cls_vec

for text in example_reviews:
    x = single_bert_embedding(text)
    pred = bert_lr.predict(x)[0]
    print(f"\nText: {text}\nPrediction: {to_sentiment(pred)}")

# ============================================================
# (d) BERT fine-tuning (TF classifier)
# ============================================================
print("\n================ (d) BERT fine-tuning ================")

def finetuned_bert_predict(text, max_length=128):
    text = clean_text_bert(text)
    tokens = tokenizer(text, truncation=True, padding=True, max_length=max_length, return_tensors="tf")
    out = ft_model(**tokens, training=False)
    pred = int(np.argmax(out.logits.numpy(), axis=1)[0])
    return pred

for text in example_reviews:
    pred = finetuned_bert_predict(text)
    print(f"\nText: {text}\nPrediction: {to_sentiment(pred)}")

"""(a) Word2Vec + Logistic Regression

The Word2Vec-based model correctly classifies clearly positive and clearly negative reviews. However, it shows limitations when handling mixed or subtle sentiment.

(b) GloVe + Logistic Regression

The GloVe-based model exhibits similar behavior to Word2Vec, but with slightly weaker performance on difficult cases.

(c) BERT Embeddings + Logistic Regression

Using BERT embeddings significantly improves performance on complex examples.

The model correctly handles:

*   Negation (“not saying it’s terrible…”)
*   Mixed sentiment (“I wanted to love it, but…”)


However, some  cases remain challenging.

The fine-tuned BERT model provides the most consistent and accurate predictions across all examples.

Key improvements include:
* Correct handling of negation and contrastive clauses
* Better interpretation of overall sentence meaning rather than isolated phrases

# XGBoost
Import XGBoostClassifier. Then, for Word2Vec, GloVe, BERT embeddings (CLS token), and BERT mean-pooled embeddings, replace the Logistic Regression classifier with XGBoostClassifier, train each model, make predictions, and store the results. Finally, update and display the summary table of model performance, sorted by F1-score.
"""

!pip install -q xgboost
import xgboost as xgb
from xgboost import XGBClassifier

print("XGBoost and XGBClassifier imported successfully.")

print("Training Word2Vec + XGBoostClassifier...")
xgb_w2v = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_w2v.fit(train_vectors, y_tok_train)

# Predict
test_predictions_xgb_w2v = xgb_w2v.predict(test_vectors)

show_results("(e) Word2Vec + XGBoost (TEST)", y_tok_test, test_predictions_xgb_w2v)
store_result("Word2Vec + XGBoost", y_tok_test, test_predictions_xgb_w2v)

print("Training GloVe + XGBoostClassifier...")
xgb_glove = XGBClassifier(eval_metric='logloss', random_state=42)
xgb_glove.fit(Xtr_glove, y_tok_train)

# Predict
test_predictions_xgb_glove = xgb_glove.predict(Xte_glove)

show_results("(f) GloVe + XGBoost (TEST)", y_tok_test, test_predictions_xgb_glove)
store_result("GloVe + XGBoost", y_tok_test, test_predictions_xgb_glove)

print("Training BERT embeddings + XGBoostClassifier...")
xgb_bert = XGBClassifier(eval_metric='logloss', random_state=42)
xgb_bert.fit(Xtr_bert, y_bert_train)

# Predict
test_predictions_xgb_bert = xgb_bert.predict(Xte_bert)

show_results("(g) BERT embeddings + XGBoost (TEST)", y_bert_test, test_predictions_xgb_bert)
store_result("BERT emb + XGBoost", y_bert_test, test_predictions_xgb_bert)

print("Training BERT mean-pooled embeddings + XGBoostClassifier...")
xgb_bert_mean = XGBClassifier(eval_metric='logloss', random_state=42)
xgb_bert_mean.fit(Xtr_bert_mean, y_bert_train)

# Predict
test_predictions_xgb_bert_mean = xgb_bert_mean.predict(Xte_bert_mean)

show_results("(h) BERT mean-pooled embeddings + XGBoost (TEST)", y_bert_test, test_predictions_xgb_bert_mean)
store_result("BERT mean-pooled + XGBoost", y_bert_test, test_predictions_xgb_bert_mean)

summary_final = pd.DataFrame(results).drop_duplicates(subset="model", keep="last").sort_values("f1", ascending=False)
print("\n=== SUMMARY (No Duplicates) ===")
print(summary_final)

"""# Conclusions

This project systematically compared classical NLP techniques with modern transformer-based models for sentiment analysis on Amazon product reviews. Based on the experimental results, we can draw the following conclusions:

### 1. Superiority of Transformers
Transformer-based models (**BERT**) significantly outperformed classical word embedding techniques (**Word2Vec**, **GloVe**). The ability of BERT to capture context and polysemy (words having different meanings based on surrounding words) proved superior to the static embeddings generated by Word2Vec and GloVe.

### 2. Fine-tuning vs. Feature Extraction
*   **Best Overall Performance:** The **Fine-tuned BERT** model achieved the highest F1-score (~97.9%). By updating the weights of the entire model end-to-end, it learned task-specific features that frozen embeddings could not capture.
*   **Feature Extraction:** Using BERT as a fixed feature extractor still yielded excellent results (F1 > 95%), offering a computationally cheaper alternative to full fine-tuning.

### 3. Impact of the Classifier
*   **XGBoost vs. Logistic Regression:** Across all embedding types (Word2Vec, GloVe, BERT), **XGBoost** consistently outperformed Logistic Regression. Its non-linear nature allowed it to better exploit the complex relationships within the embedding space.
*   For example, switching from Logistic Regression to XGBoost improved the BERT mean-pooled F1-score from ~95.7% to ~96.6%.

# Exploratory Analysis

Class distribution
"""

label_counts = df["label"].value_counts()

plt.figure()
label_counts.plot(kind="bar")
plt.xticks([0,1], ["Negative", "Positive"], rotation=0)
plt.title("Class distribution")
plt.ylabel("Number of reviews")
plt.show()

"""Word2Vec Feature Importance"""

# Logistic Regression feature importance

coefficients = model.coef_[0]

plt.figure()
plt.hist(coefficients, bins=50)
plt.title("Distribution of Logistic Regression coefficients (Word2Vec)")
plt.xlabel("Coefficient value")
plt.ylabel("Frequency")
plt.show()

"""Word clouds for positive and negative reviews.

"""

from wordcloud import WordCloud
# ------------------------------------------------------------
# Select only POSITIVE reviews
# ------------------------------------------------------------
positive_reviews = df[df["label"] == 1]["tokens"]

# Flatten list of token lists into one list of words
positive_words = []
for review in positive_reviews:
    positive_words.extend(review)

# Convert list of words to a single string
positive_text = " ".join(positive_words)

# ------------------------------------------------------------
# Generate and display Word Cloud
# ------------------------------------------------------------
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    max_words=100
).generate(positive_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud – Positive Reviews")
plt.show()

# Select only NEGATIVE reviews
negative_reviews = df[df["label"] == 0]["tokens"]

# Flatten list of token lists into one list of words
negative_words = []
for review in negative_reviews:
    negative_words.extend(review)

# Convert list of words to a single string
negative_text = " ".join(negative_words)

# Generate and display Word Cloud
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    max_words=100
).generate(negative_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud – Negative Reviews")
plt.show()

"""# K-Means Topic Modeling - In progress

"""

# Group by 'Brand Name' to see review volume and average sentiment
brand_analysis = df.groupby('Brand Name').agg(
    Total_Reviews=('label', 'count'),
    Percent_Positive=('label', 'mean')
).sort_values(by='Total_Reviews', ascending=False)

# Show top 20 brands
print("Top 20 Tech Companies by Review Volume:")
display(brand_analysis.head(20))

# Plot sentiment for the top 10 most reviewed brands
top_10_brands = brand_analysis.head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_10_brands.index, y=top_10_brands['Percent_Positive'], hue=top_10_brands.index, palette='viridis', legend=False)
plt.title("Positive Sentiment Ratio by Top Tech Companies")
plt.ylabel("Ratio of Positive Reviews")
plt.xlabel("Brand Name")
plt.xticks(rotation=45)
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 1. Define Strict Phone-Related Dictionary
phone_keywords = [
    'battery', 'screen', 'camera', 'charge', 'charging',
    'sim', 'port', 'button', 'volume', 'sound', 'speaker',
    'mic', 'wifi', 'signal', 'service', 'price', 'case', 'glass'
]

# 2. Create 4 specific subsets (Apple Pos/Neg, Samsung Pos/Neg)
# Sampling 50 reviews for each to keep the visualization manageable
N = 50
df_apple_pos = df[(df['Brand Name'] == 'Apple') & (df['label'] == 1)].sample(N, random_state=42)
df_apple_neg = df[(df['Brand Name'] == 'Apple') & (df['label'] == 0)].sample(N, random_state=42)

df_samsung_pos = df[(df['Brand Name'] == 'Samsung') & (df['label'] == 1)].sample(N, random_state=42)
df_samsung_neg = df[(df['Brand Name'] == 'Samsung') & (df['label'] == 0)].sample(N, random_state=42)

# Combine in a specific order for consistent indexing if needed,
# but we will slice the dataframe for plotting.
df_brand_subset = pd.concat([df_apple_pos, df_apple_neg, df_samsung_pos, df_samsung_neg])

# 3. Vectorize using ONLY the phone dictionary
# vocabulary=phone_keywords forces the vectorizer to ignore all other words
cv_strict = CountVectorizer(vocabulary=phone_keywords)
X_strict = cv_strict.fit_transform(df_brand_subset['Reviews'].astype(str))
feature_names = cv_strict.get_feature_names_out()

# 4. Create DataFrame
X_dense = X_strict.toarray()
df_counts = pd.DataFrame(X_dense, columns=feature_names)

# Slices (50 rows each)
df_ap = df_counts.iloc[0:50]    # Apple Positive
df_an = df_counts.iloc[50:100]  # Apple Negative
df_sp = df_counts.iloc[100:150] # Samsung Positive
df_sn = df_counts.iloc[150:200] # Samsung Negative

# 5. Visualization (2x2 Grid)
fig, axes = plt.subplots(2, 2, figsize=(20, 16), sharey=True, sharex=True)

# Row 1: Apple
sns.heatmap(df_ap.T, cmap='Greys', cbar=False, xticklabels=False, ax=axes[0, 0])
axes[0, 0].set_title("Apple - Positive")
axes[0, 0].set_ylabel("Terms")

sns.heatmap(df_an.T, cmap='Greys', cbar=True, xticklabels=False, ax=axes[0, 1])
axes[0, 1].set_title("Apple - Negative")
axes[0, 1].set_ylabel("")
# Row 2: Samsung
sns.heatmap(df_sp.T, cmap='Greys', cbar=False, xticklabels=False, ax=axes[1, 0])
axes[1, 0].set_title("Samsung - Positive")
axes[1, 0].set_ylabel("Terms")
axes[1, 0].set_xlabel("Reviews (50 Samples)")

sns.heatmap(df_sn.T, cmap='Greys', cbar=True, xticklabels=False, ax=axes[1, 1])
axes[1, 1].set_title("Samsung - Negative")
axes[1, 1].set_ylabel("")
axes[1, 1].set_xlabel("Reviews (50 Samples)")

plt.tight_layout()
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

def plot_elbow_and_cluster(df_subset, sentiment_name, k=3):
    # Vectorize
    tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
    X = tfidf.fit_transform(df_subset['Reviews'].astype(str))

    # --- Elbow Method ---
    inertias = []
    K_range = range(1, 11)
    print(f"Calculating Elbow Curve for {sentiment_name}...")
    for i in K_range:
        km = KMeans(n_clusters=i, random_state=42, n_init='auto')
        km.fit(X)
        inertias.append(km.inertia_)

    plt.figure(figsize=(8, 4))
    plt.plot(K_range, inertias, 'bx-')
    plt.xlabel('Number of Clusters (k)')
    plt.ylabel('Inertia')
    plt.title(f'Elbow Method for {sentiment_name}')
    plt.grid(True)
    plt.show()

    # --- Clustering ---
    print(f"\nRunning K-Means for {sentiment_name} with k={k}...")
    kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
    kmeans.fit(X)

    # Print Top Terms
    feature_names = tfidf.get_feature_names_out()
    for topic_idx, topic in enumerate(kmeans.cluster_centers_):
        top_features = [feature_names[i] for i in topic.argsort()[:-11:-1]]
        print(f"Cluster {topic_idx}: {', '.join(top_features)}")
    print("-"*50)

# Run Analysis
print("=== Positive Reviews Analysis ===")
plot_elbow_and_cluster(df[df['label'] == 1], "Positive Reviews", k=5)

print("\n=== Negative Reviews Analysis ===")
plot_elbow_and_cluster(df[df['label'] == 0], "Negative Reviews", k=8)

from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import CountVectorizer

# 1. Define a Whitelist of "Hardware/Software" Terms
# This ensures we ONLY get these terms and don't accidentally ignore valid ones or include noise.
hw_sw_whitelist = [
    'battery', 'screen', 'camera', 'sim', 'card',
    'charger', 'charging', 'charge', 'port',
    'speaker', 'sound', 'volume', 'button', 'keys', 'keyboard',
    'mic', 'microphone', 'wifi', 'signal', 'service', 'network', 'data',
    'memory', 'storage', 'ram', 'space',
    'case', 'glass', 'display', 'pixel', 'resolution',
    'android', 'ios', 'app', 'apps', 'software', 'update', 'os',
    'bluetooth', 'connection', 'usb', 'headphone', 'lens', 'flash'
]

# 2. Count frequencies of ONLY these words in the dataset
cv_check = CountVectorizer(vocabulary=hw_sw_whitelist)
X_check = cv_check.fit_transform(df['Reviews'].astype(str))
sum_counts = X_check.sum(axis=0)

# Sort by frequency
freqs = [(word, sum_counts[0, idx]) for word, idx in cv_check.vocabulary_.items()]
freqs = sorted(freqs, key=lambda x: x[1], reverse=True)

# Select the top 12 most frequent terms from our whitelist
top_features = [f[0] for f in freqs if f[1] > 0][:12]

print(f"Final Whitelisted Top Features:\n{top_features}\n")

# Initialize Cluster Label column in the main dataframe
df['Cluster_Label'] = None

# 3. Cluster and Plot Function (Modified to Save Labels)
def cluster_and_plot_heatmap(df_subset, title, n_clusters=5, prefix="Clust"):
    # Vectorize using ONLY the selected top features
    cv = CountVectorizer(vocabulary=top_features)
    X = cv.fit_transform(df_subset['Reviews'].astype(str))
    feature_names = cv.get_feature_names_out()

    # Fit K-Means
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
    kmeans.fit(X)

    # --- SAVE LABELS TO MAIN DATAFRAME ---
    # We use the index of df_subset to update the correct rows in the main df
    labels = [f"{prefix}_{i}" for i in kmeans.labels_]
    df.loc[df_subset.index, 'Cluster_Label'] = labels

    # Get Cluster Centers (Centroids)
    centers = kmeans.cluster_centers_

    # Create a DataFrame for the heatmap
    df_centers = pd.DataFrame(centers, columns=feature_names)
    df_centers.index = [f"Cluster {i}" for i in range(n_clusters)]

    # Plot Heatmap
    plt.figure(figsize=(14, 6))
    sns.heatmap(df_centers, cmap='Greys', annot=True, fmt=".2f")
    plt.title(f"{title} - Topic Cluster Centroids (HW/SW Whitelist)")
    plt.xlabel("Hardware/Software Keywords")
    plt.ylabel("Clusters")
    plt.show()

    # Statistics
    df_clustered = df_subset.copy()
    df_clustered['Cluster'] = kmeans.labels_

    print(f"\nCluster Statistics ({title}):")
    print("-" * 60)
    for i in range(n_clusters):
        cluster_data = df_clustered[df_clustered['Cluster'] == i]
        if not cluster_data.empty:
            median_rate = cluster_data['Rating'].median()
            valid_brands = cluster_data['Brand Name'].dropna()
            brand_str = "No Brand Data"
            if not valid_brands.empty:
                top_brand = valid_brands.value_counts().idxmax()
                count = valid_brands.value_counts().max()
                total = len(valid_brands)
                brand_str = f"{top_brand} ({count}/{total})"
            print(f"Cluster {i}: Median Rating = {median_rate} | Top Brand = {brand_str}")
    print("-" * 60)

# Run for Positive Reviews (k=5)
print("Analyzing Positive Reviews...")
cluster_and_plot_heatmap(df[df['label'] == 1], "Positive Reviews", n_clusters=5, prefix="Pos")

# Run for Negative Reviews (k=8)
print("\nAnalyzing Negative Reviews...")
cluster_and_plot_heatmap(df[df['label'] == 0], "Negative Reviews", n_clusters=8, prefix="Neg")

print("\nCluster Labels assigned to DataFrame:")
display(df[['Reviews', 'label', 'Cluster_Label']].head())

