# -*- coding: utf-8 -*-
"""Sleep_mbads_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEfSRhP5tgFSIduwuWayVQPdjGyELLIu

# Library Imports and Preprocessing
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.neighbors import NearestNeighbors

from scipy.cluster.hierarchy import dendrogram, linkage

"""Load Dataset & Preprocessing"""

csv_path = "/content/drive/MyDrive/Sleep_health_and_lifestyle_dataset.csv"

df = pd.read_csv(csv_path)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nSleep Disorder value counts (including NaN):")
print(df["Sleep Disorder"].value_counts(dropna=False))

for x in df.columns:
  print(x,'   ', df[x].unique())

# Replace missing Sleep Disorder with "None"
df["Sleep Disorder"] = df["Sleep Disorder"].fillna("None")
# "Normal Weight" and "Normal" are the same category in BMI
if "BMI Category" in df.columns:
    df["BMI Category"] = df["BMI Category"].replace("Normal Weight", "Normal")

df = df.drop(columns=["Person ID"])

"""New Features"""

# Pulse Pressure
bp_split = df["Blood Pressure"].astype(str).str.split("/", expand=True)
df["Systolic"] = bp_split[0].astype(int)
df["Diastolic"] = bp_split[1].astype(int)

df.drop(columns=["Blood Pressure"], inplace=True)

df["Pulse Pressure"] = df["Systolic"] - df["Diastolic"]

# Steps per Activity
df["Steps per Activity"] = df["Daily Steps"] / df["Physical Activity Level"].replace(0, np.nan)
df["Steps per Activity"] = df["Steps per Activity"].fillna(df["Steps per Activity"].median())

for x in df.columns:
  print(x,'   ', df[x].unique())

print("\nAfter preprocessing:")
print(df.head())

# --- Correlation Heatmap ---
import seaborn as sns
plt.figure(figsize=(10, 8))
# Select only numeric columns for correlation
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

df.to_csv("sleep_dataset_preprocessed.csv", index=False)

"""# Classification

Models: Decision Tree (C4.5-like), kNN, Naive Bayes, Random Forest, AdaBoost
"""

# Separate X (features) and y (target)
y = df["Sleep Disorder"]
X = df.drop(columns=["Sleep Disorder"])


# This converts Gender, Occupation, BMI Category into numeric columns
X_encoded = pd.get_dummies(X, drop_first=True)

print("X_encoded shape:", X_encoded.shape)

# Train-test split (stratify keeps class proportions)
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y)

# scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Create models (simple parameters, not advanced tuning)
dt = DecisionTreeClassifier(criterion="entropy", random_state=42)
knn = KNeighborsClassifier(n_neighbors=5)
nb = GaussianNB()
rf = RandomForestClassifier(n_estimators=200, random_state=42)
ada = AdaBoostClassifier(n_estimators=200, random_state=42)

models = [
    ("Decision Tree (entropy)", dt, False),
    ("kNN (k=5)", knn, True),
    ("Naive Bayes (Gaussian)", nb, True),
    ("Random Forest", rf, False),
    ("AdaBoost", ada, False),]

# Train, predict, evaluate
results = []

for name, model, use_scaled in models:
    if use_scaled:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results.append((name, acc))

    print("\n--------------------------------------------")
    print("Model:", name)
    print("Accuracy:", acc)
    print("\nClassification report:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred, labels=["None", "Insomnia", "Sleep Apnea"])
    print("Confusion matrix (rows=true, cols=pred) with order [None, Insomnia, Sleep Apnea]:")
    print(cm)

"""Summary"""

for name, acc in sorted(results, key=lambda x: x[1], reverse=True):
    print(f"{name:25s} -> {acc:.4f}")
from sklearn.metrics import ConfusionMatrixDisplay

# Identify the best model from results
best_name = sorted(results, key=lambda x: x[1], reverse=True)[0][0]
best_model_info = next(m for m in models if m[0] == best_name)
name, model, use_scaled = best_model_info

# Predict
if use_scaled:
    y_p = model.predict(X_test_scaled)
else:
    y_p = model.predict(X_test)

# Plot
plt.figure(figsize=(6,5))
ConfusionMatrixDisplay.from_predictions(y_test, y_p, cmap='Blues', xticks_rotation='vertical')
plt.title(f"Confusion Matrix: {name}")
plt.show()

# --- Feature Importance (Random Forest) ---

importances = rf.feature_importances_
feature_names = X_train.columns

# Create DataFrame for better visualization
df_imp = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
df_imp = df_imp.sort_values('Importance', ascending=False).head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=df_imp, palette='magma')
plt.title('Top 10 Feature Importances (Random Forest)')
plt.show()

"""# Clustering"""

# Select numeric features
# Keep numeric lifestyle/health features
num_cols = [
    "Age", "Sleep Duration", "Quality of Sleep", "Physical Activity Level",
    "Stress Level", "Heart Rate", "Daily Steps", "Systolic", "Diastolic"]

X_clust = df[num_cols].copy()

# Scale numeric data for distance-based clustering
scaler2 = StandardScaler()
X_clust_scaled = scaler2.fit_transform(X_clust)

print("Clustering matrix shape:", X_clust_scaled.shape)

""" B1) k-means + elbow method

"""

print("\n--- B1) k-means + elbow ---")
inertias = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_clust_scaled)
    inertias.append(kmeans.inertia_)

plt.figure()
plt.plot(list(K_range), inertias, marker="o")
plt.title("Elbow Method (k-means)")
plt.xlabel("k")
plt.ylabel("Inertia")
plt.show()

# Choosing k based on elbow
k_choice = 5
kmeans_final = KMeans(n_clusters=k_choice, random_state=42, n_init=10)
labels_kmeans = kmeans_final.fit_predict(X_clust_scaled)

df_kmeans = df.copy()
df_kmeans["Cluster_kmeans"] = labels_kmeans

print("k-means cluster counts:")
print(df_kmeans["Cluster_kmeans"].value_counts())

print("\nCluster profiles (mean of numeric features):")
print(df_kmeans.groupby("Cluster_kmeans")[num_cols].mean())

# --- PCA Visualization ---
from sklearn.decomposition import PCA
import seaborn as sns

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_clust_scaled)

plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=labels_kmeans, palette='viridis', s=100)
plt.title("PCA Visualization of K-Means Clusters")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(title='Cluster')
plt.show()

print("\n=== Detailed Descriptive Statistics by Cluster (k-means) ===")
# Iterate through each cluster to print readable stats
for cluster_id in sorted(df_kmeans["Cluster_kmeans"].unique()):
    print(f"\nCluster {cluster_id}:")
    # Describe numeric features for this cluster and transpose for readability
    desc = df_kmeans[df_kmeans["Cluster_kmeans"] == cluster_id][num_cols].describe().T
    print(desc)

# Number of Sleep Disorders per Cluster
print("\n--- Sleep Disorder Counts per Cluster (k-means) ---")
disorder_per_cluster = df_kmeans.groupby(["Cluster_kmeans", "Sleep Disorder"]).size().unstack(fill_value=0)
print(disorder_per_cluster)

# Total Number of People per Sleep Disorder Class
print("\n--- Total People per Sleep Disorder Class ---")
print(df["Sleep Disorder"].value_counts())

"""Cluster 0 (Older, Good Sleep, High BP): Average age ~57. High sleep duration (8.1h) and quality (9/10), low stress, but higher blood pressure (Systolic ~140).

Cluster 1 (Younger, Stressed, Poor Sleep): Average age ~39. Lower sleep duration (6.4h) and quality (6.2/10), higher stress levels (6.5), and lower daily steps.

Cluster 2 (Youngest, Healthy, Active): Average age ~37. Good sleep (7.5h), physically active (7600 steps), and moderate stress.

Cluster 3 (Middle-aged, Very Rested, Sedentary): Average age ~53. Excellent sleep (8.4h) and quality (9/10), but very low physical activity (level 30).

Cluster 4 (Middle-aged, High Stress, Active but Deprived): Average age ~50. Very high physical activity (level 90) and steps (10,000), but high stress (8.0) and poor sleep duration (6.1h).

B2) Hierarchical (Agglomerative) + dendrogram
"""

print("\n--- B2) Agglomerative + dendrogram ---")

Z = linkage(X_clust_scaled, method="ward")

plt.figure(figsize=(10, 5))
dendrogram(Z, truncate_mode="lastp", p=20)  # show last 20 merges (simpler view)
plt.title("Dendrogram (Ward linkage) - truncated view")
plt.xlabel("Cluster size / sample group")
plt.ylabel("Distance")
plt.show()

# Choose number of clusters from dendrogram
n_clusters_h = 4
agg = AgglomerativeClustering(n_clusters=n_clusters_h, linkage="ward")
labels_agg = agg.fit_predict(X_clust_scaled)

df_agg = df.copy()
df_agg["Cluster_agg"] = labels_agg

print("Agglomerative cluster counts:")
print(df_agg["Cluster_agg"].value_counts())

print("\nCluster profiles (mean of numeric features):")
print(df_agg.groupby("Cluster_agg")[num_cols].mean())

"""B3) DBSCAN + k-distance graph"""

# k-distance graph: choose k = 4 or 5 (common rule)
k = 4
nn = NearestNeighbors(n_neighbors=k)
nn.fit(X_clust_scaled)
distances, indices = nn.kneighbors(X_clust_scaled)

# distances[:, k-1] is the distance to the k-th nearest neighbor
k_dist = np.sort(distances[:, k-1])

plt.figure()
plt.plot(k_dist)
plt.title(f"k-distance graph (k={k})")
plt.xlabel("Points sorted by distance")
plt.ylabel(f"Distance to {k}-th nearest neighbor")
plt.show()

# Choose eps from the "elbow" of this plot (example eps=0.9)
eps_choice = 1
min_samples_choice = k

db = DBSCAN(eps=eps_choice, min_samples=min_samples_choice)
labels_db = db.fit_predict(X_clust_scaled)

df_db = df.copy()
df_db["Cluster_dbscan"] = labels_db

print("DBSCAN labels counts (note: -1 = noise):")
print(df_db["Cluster_dbscan"].value_counts())

# show cluster profiles only for non-noise clusters
df_db_clean = df_db[df_db["Cluster_dbscan"] != -1]
if len(df_db_clean) > 0 and df_db_clean["Cluster_dbscan"].nunique() > 0:
    print("\nDBSCAN cluster profiles (mean of numeric features, excluding noise):")
    print(df_db_clean.groupby("Cluster_dbscan")[num_cols].mean())

"""# Association Rule Mining (Apriori)"""

# Make a categorical (binned) dataset
df_cat = df.copy()

# Discretize numeric columns into 3 bins: Low/Medium/High (simple)
def bin3(series, colname):
    # qcut makes bins with approx equal counts
    # duplicates='drop' avoids errors if many equal values
    binned = pd.qcut(series, q=3, duplicates="drop", labels=["Low", "Med", "High"])
    return colname + "=" + binned.astype(str)

df_cat_items = pd.DataFrame()

# Keep original categorical columns as "Col=Value"
cat_cols = ["Gender", "Occupation", "BMI Category", "Sleep Disorder"]
for c in cat_cols:
    df_cat_items[c] = c + "=" + df_cat[c].astype(str)

# Add binned numeric columns
for c in num_cols:
    df_cat_items[c] = bin3(df_cat[c], c)

print("Example items row:")
print(df_cat_items.iloc[0].tolist())

# 2) Transactions list (each row -> list of items)
transactions = df_cat_items.values.tolist()

"""Apriori"""

def support_count(itemset, transactions):
    """Count how many transactions contain the itemset."""
    count = 0
    itemset = set(itemset)
    for t in transactions:
        if itemset.issubset(set(t)):
            count += 1
    return count

def apriori(transactions, min_support=0.10):
    """
    Returns frequent itemsets with support >= min_support.
    Output: dict {frozenset(items): support}
    """
    n = len(transactions)
    # C1: all single items
    items = sorted(list(set([item for t in transactions for item in t])))
    L = {}
    Lk = {}

    # L1
    for it in items:
        c = support_count([it], transactions)
        sup = c / n
        if sup >= min_support:
            Lk[frozenset([it])] = sup

    L.update(Lk)
    k = 2

    while len(Lk) > 0:
        # generate candidates Ck from Lk-1
        prev_itemsets = list(Lk.keys())
        candidates = set()

        for i in range(len(prev_itemsets)):
            for j in range(i+1, len(prev_itemsets)):
                union = prev_itemsets[i].union(prev_itemsets[j])
                if len(union) == k:
                    candidates.add(union)

        # count supports for candidates
        Lk_new = {}
        for cand in candidates:
            c = support_count(list(cand), transactions)
            sup = c / n
            if sup >= min_support:
                Lk_new[frozenset(cand)] = sup

        L.update(Lk_new)
        Lk = Lk_new
        k += 1

    return L

def generate_rules(freq_itemsets, min_conf=0.6):
    """
    Create association rules from frequent itemsets.
    Rule: A -> B
    Compute support(A∪B), confidence, lift
    Returns list of dict rules.
    """
    rules = []
    for itemset, sup_ab in freq_itemsets.items():
        if len(itemset) < 2:
            continue

        items = list(itemset)
        # all possible splits A/B
        for i in range(1, len(items)):
            # simple split generation using combinations
            from itertools import combinations
            for A in combinations(items, i):
                A = frozenset(A)
                B = itemset.difference(A)

                sup_a = freq_itemsets.get(A, None)
                sup_b = freq_itemsets.get(B, None)

                # If not in dictionary, skip (usually ok because B might not be frequent alone)
                if sup_a is None or sup_a == 0:
                    continue

                conf = sup_ab / sup_a

                # Lift needs support(B). If B is not frequent alone, compute directly (simple)
                if sup_b is None:
                    sup_b = support_count(list(B), transactions) / len(transactions)

                if sup_b == 0:
                    continue

                lift = conf / sup_b

                if conf >= min_conf:
                    rules.append({
                        "A": A,
                        "B": B,
                        "support": sup_ab,
                        "confidence": conf,
                        "lift": lift
                    })

    # sort by lift then confidence
    rules = sorted(rules, key=lambda x: (x["lift"], x["confidence"]), reverse=True)
    return rules

# Run Apriori + Rules
min_support = 0.10
min_conf = 0.60

freq_itemsets = apriori(transactions, min_support=min_support)
print(f"Frequent itemsets found: {len(freq_itemsets)} (min_support={min_support})")

rules = generate_rules(freq_itemsets, min_conf=min_conf)
print(f"Rules found: {len(rules)} (min_conf={min_conf})")

# Print top 10 rules (you can copy these into your report and comment them)
top_n = 10
print("\nTop rules by Lift/Confidence:")
for i, r in enumerate(rules[:top_n], start=1):
    A_str = ", ".join(sorted(list(r["A"])))
    B_str = ", ".join(sorted(list(r["B"])))
    print("--------------------------------------------------")
    print(f"Rule {i}:  IF [{A_str}]  THEN [{B_str}]")
    print(f"Support: {r['support']:.3f}  Confidence: {r['confidence']:.3f}  Lift: {r['lift']:.3f}")

# Filter Association Rules for Sleep Disorders
target_disorders = {'Sleep Disorder=Insomnia', 'Sleep Disorder=Sleep Apnea'}

filtered_rules = []
for r in rules:
    # Check if any target disorder is in the Consequent (B)
    if not r['B'].isdisjoint(target_disorders):
        if r['lift'] > 1.2:
            filtered_rules.append(r)

print(f"\n=== Top 20 Association Rules leading to Insomnia or Sleep Apnea (out of {len(filtered_rules)} found) ===")

for i, r in enumerate(filtered_rules[:10], start=1):
    A_str = ", ".join(sorted(list(r["A"])))
    B_str = ", ".join(sorted(list(r["B"])))
    print(f"Rule {i}: IF [{A_str}] \n         THEN [{B_str}] \n         (Lift: {r['lift']:.2f}, Conf: {r['confidence']:.2f})\n")

if not filtered_rules:
    print("No specific rules found leading to Sleep Disorders with current thresholds.")